# Minimal Sphinx Makefile for Linux/CI

SPHINXBUILD = sphinx-build
SOURCEDIR   = source
BUILDDIR    = build

.PHONY: html clean

html:
	$(SPHINXBUILD) -M html $(SOURCEDIR) $(BUILDDIR)

clean:
	rm -rf $(BUILDDIR)/*
